[project]
name = 'Decentralized-Student-Loan-Smart-Contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Decentralized-Student-Loan-Smart-Contracts]
path = 'contracts/Decentralized-Student-Loan-Smart-Contracts.clar'
clarity_version = 3
epoch = 3.1
[contracts.sponsor-payments]
path = 'contracts/sponsor-payments.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
